language: python
sudo: false

python:
  - "2.7"
  - "3.5"

install:
  - conda update --yes conda
  - conda create -n testenv --yes numpy scipy pandas!=0.18.0 nose python=$TRAVIS_PYTHON_VERSION
  - conda install -n testenv -c soft-matter --yes pims trackpy
  - source activate testenv
  - python setup.py build_ext install


before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ];
    then
        wget http://repo.continuum.io/miniconda/Miniconda-3.7.3-Linux-x86_64.sh -O miniconda.sh;
    else
        wget http://repo.continuum.io/miniconda/Miniconda3-3.7.3-Linux-x86_64.sh -O miniconda.sh;
    fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/mc
  - export PATH=/home/travis/mc/bin:$PATH

script:
    - nosetests --nologcapture

